### PR TITLE
Add frozen_string_literal to all files and some static code cleanup

### PR DESCRIPTION
**Pull request by geophilusd**

### CODE REVIEW

**Comment by mullermp** [comment]
Thanks for opening a pull request. Was this clean up done through Rubocop? I ran the CI but there's some issues.

**Comment by mullermp** [comment]
This library supports old Ruby versions, so some of the Rubocop cleanups are actually just breaking. For Ruby 1.9 support, I believe the last Rubocop version that supports it as a target version is 0.41.0.

**Comment by geophilusd** [comment]
Yes, I used rubocop for it. Have made necessary changes.

**Comment by mullermp** [comment]
Changes look good. Thanks! I'll get this merged, and it will be released next time we have a feature to add/issue to fix.

**Review by alextwoods — APPROVED** [review]

**Pull request merged**
