### PR TITLE
Rewritten interpreter and AST optimizations

### PR DESCRIPTION
**Pull request by iconara**
This adds a new JIT-friendly interpreter and AST optimizations that makes evaluating expressions much faster, 2-4x for the benchmarks I'm running.

The main thing that has changes is that instead of `TreeInterpreter#dispatch` walking the AST using a big case statement, each AST node contains can interpret itself. This removes almost all of the branching from the interpretation, and it makes it easier for JITing runtimes like JRuby to optimize the interpreter code. In the current implementation quite a lot of time is spent just running `Symbol#===` because of all of the cases that needs to be checked to decide which code to run for the next node in the AST, this has been completely side-stepped since each node calls the next node directly.

I've tried to move as many decisions as possible to the parser phase to avoid branching in the interpreter. For example, each function is its own AST node, instead of having a case statement that needs to be run at interpretation. The same goes for projections, comparisons, etc.

I've also started on AST optimizations, such as flattening long chains of field and index lookups, conditions with literals, and a few other things. This part is a work in progress, but it can speed up some expressions by 20-30%.

I'd like to work on this a bit more, I don't think it's ready to merge yet. The tests all pass, but I think there's a need for some more tests around the optimizer, for example.

I'm also considering adding options for the optimizer to assume that values will always be hashes, never structs, and always have strings, never symbol keys (I would of course not change the current defaults, this would be an option only), because this would enable another level of optimizations that are not currently possible.

### CODE REVIEW

**Comment by trevorrowe** [comment]
I need to apologize for forgetting about this pull-request. I do intend to take a closer look at this *soon*. Jmespath has recently added support at the language level for python style ranges and so I intend to add support for these as well.

**Comment by iconara** [comment]
Thanks. I put the work aside for a while, partly to get your comments and partly because the project where we were going to use JMESPath got put on the back burner. I'd love to see this merged in one form or another, though, so when you have time your comments and feedback would be much appreciated.

**Comment by bjorne** [comment]
While @iconara's specific use-case for this change got halted, we are now using this branch in production with success. I just wanted to make a bump here and report that we have not yet found any unexpected behavior. Would love to see this merged.

**Comment by iconara** [comment]
@trevorrowe is there any chance of this getting merged and released? Is there anything we can do to help?

**Comment by trevorrowe** [comment]
Thanks for being patient. I did get this merged, tested and pushed to master. I also took the opportunity to update the bundled suite of compliance tests to add newer functionality. I'll try to get this released shortly.

**Comment by iconara** [comment]
Thanks!

We forked and released our own gem, [burtpath](https://github.com/burtcorp/burtpath), but we'll probably switch back to jmespath.rb. There are some more contributions coming.

**Pull request merged**
